  import { defineConfig, devices } from '@playwright/test';
    
    import dotenv from 'dotenv';
    
    dotenv.config({
  path: './env/.env.dev'
  });
    
    export default defineConfig({

  testDir: './tests',

  timeout: 30000,

  fullyParallel: true,

  retries: process.env.CI ? 2 : 0,

  workers: process.env.CI ? 1 : undefined,

  reporter: [
    ['html'],
    ['list']
  ],

  use: {

    baseURL: process.env.BASE_URL,

    headless: process.env.CI ? true : false,

    screenshot: 'only-on-failure',

    video: 'retain-on-failure',

    trace: 'retain-on-failure'
  },

  projects: [
    {
      name: 'chromium',
      use: {
             ...devices['Desktop Chrome']
      }
    }
  ]
  });